-- 우유와 요거트가 담긴 장바구니
SELECT DISTINCT A.CART_ID
  FROM 
    (SELECT CART_ID
       FROM CART_PRODUCTS 
      WHERE NAME='우유') AS A
INNER JOIN
    (SELECT CART_ID
       FROM CART_PRODUCTS
      WHERE NAME='요거트') AS B
ON A.CART_ID=B.CART_ID
ORDER BY CART_ID